<a href="https://colab.research.google.com/github/mareeswarisuba123-ctrl/Data-Analytics-using-python-project/blob/main/mini_project_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt

uploaded=files.upload()

df=pd.read_csv("products-100.csv")

print(df)

Saving products-100.csv to products-100.csv
    Index                                   Name  \
0       1   Compact Printer Air Advanced Digital
1       2                                 Tablet
2       3                   Smart Blender Cooker
3       4           Advanced Router Rechargeable
4       5           Portable Mouse Monitor Phone
..    ...                                    ...
95     96                                 Router
96     97     Fast Thermostat Microphone Scooter
97     98  Eco Heater Toaster Stove Silent Sense
98     99               Clean Blender Scale Lite
99    100                             Smart Lamp

                                          Description  \
0       Situation organization these memory much off.
1         Discussion loss politics free one thousand.
2                                   No situation per.
3                     For force gas energy six laugh.
4   Feeling back religious however author room sci...
..                                                ...
95                   Investment everything story buy.
96                     Nature notice themselves news.
97                   Understand still or summer rule.
98                               Final art some push.
99                         However public major baby.

                          Brand                Category  Price Currency  \
0       Garner, Boyle and Flynn      Books & Stationery    265      USD
1                   Mueller Inc        Shoes & Footwear    502      USD
2    Lawson, Keller and Winters      Kitchen Appliances    227      USD
3            Gallagher and Sons      Kitchen Appliances    121      USD
4                     Irwin LLC          Kids' Clothing      1      USD
..                          ...                     ...    ...      ...
95                 Atkinson Inc     Laptops & Computers    375      USD
96                     Shea Ltd  Beauty & Personal Care    289      USD
97                     West Ltd       Cleaning Supplies    232      USD
98     Bell, Gamble and Barrett        Camping & Hiking    241      USD
99  Hebert, Hughes and Trujillo          Bedding & Bath     71      USD

    Stock            EAN        Color         Size   Availability  Internal ID
0     774  2091465262179  ForestGreen        Large      pre_order           56
1      81  5286196620740        Black      8x10 in       in_stock           29
2     726  1282898648918    SlateGray           XS       in_stock           70
3     896  3879177514583    PaleGreen            L   discontinued           31
4     925  9055773261265     SeaShell   100x200 mm   discontinued           10
..    ...            ...          ...          ...            ...          ...
95    703  3330396409604    Gainsboro      8x10 in  limited_stock           55
96    727  9265397743935        White  Extra Large      backorder           25
97    998  5505866454530      OldLace        Small  limited_stock           20
98    391  3893594435450   Aquamarine       5x7 in  limited_stock            5
99    518  8264263605712        Brown       Medium  limited_stock            3

[100 rows x 13 columns]

Add `%load_ext cudf.pandas` before importing pandas to speed up operations using GPU

In [ ]:
total_sales=df(customers_Amount].sum()
print("total sales:",total")

In [ ]:
df.head(20)

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,4,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,121,USD,896,3879177514583,PaleGreen,L,discontinued,31
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10
5,6,Radio,Character prove growth contain serious customer.,"Benjamin, Nelson and Hancock",Skincare,426,USD,549,1150028980156,CornflowerBlue,30x40 cm,pre_order,60
6,7,Ultra Projector Oven Thermostat Prime Advanced,Pattern possible look necessary indicate work ...,"Mccoy, Waters and Rose",Laptops & Computers,68,USD,870,5029747624534,Purple,S,discontinued,86
7,8,Webcam Stove Grill,Deep area join carry age.,Morrow and Sons,Automotive,159,USD,584,9883725074294,MediumOrchid,8x10 in,pre_order,50
8,9,Eco Radio,Know father for act let.,"Edwards, Odonnell and Conley",Skincare,454,USD,499,1773215338624,DimGray,Medium,pre_order,88
9,10,Ultra Powerbank Brush Charger Max,Meeting add economic task outside.,"Brennan, Archer and Rosales",Fitness Equipment,845,USD,564,4877111475333,Silver,Extra Large,discontinued,88
10,11,Wireless Dock,Whole bill sound whether will.,Russo-West,Health & Wellness,257,USD,168,9680811891595,Wheat,Extra Large,pre_order,30
11,12,Fast Camera Router Fan Smart,Various above trouble itself crime form.,Vazquez and Sons,Cleaning Supplies,221,USD,672,8567222480604,MidnightBlue,Medium,pre_order,32
12,13,Heater Radio,Ten do evidence billion perhaps read bank enter.,Delgado-Blackwell,Cycling,689,USD,156,5686660235911,Orange,L,pre_order,57
13,14,Smart Trimmer Webcam Heater,Example available better.,Contreras PLC,Automotive,279,USD,818,1941032767914,Gainsboro,XXL,pre_order,66
14,15,Webcam Dock Heater,State yet soon traditional your deal.,"Juarez, Powell and Travis",Cleaning Supplies,101,USD,159,1438856474369,Sienna,30x40 cm,pre_order,88
15,16,Automatic Watch Lite Sense,As east entire positive source their.,"Reid, Chase and Ballard",Team Sports,316,USD,329,3500722785805,Tan,5x7 in,limited_stock,44
16,17,Eco Iron Monitor Air,Color single indeed yard event popular food boy.,Barker-Murphy,Automotive,982,USD,47,7887280730963,OliveDrab,XL,out_of_stock,79
17,18,Digital Tablet Router Printer Lite,Accept campaign every research test.,Vazquez-Smith,Health & Wellness,3,USD,732,4170125892616,LemonChiffon,10x10 cm,backorder,87
18,19,Eco Freezer Powerbank Watch,Of price visit interesting enter three set.,"Pruitt, Higgins and Barnett",Cleaning Supplies,340,USD,618,6340907128242,Cyan,S,limited_stock,21
19,20,Cooler Fan,Fall billion city share.,Bray LLC,Smartphones,529,USD,844,267078141619,Bisque,XS,backorder,22

In [ ]:
df=df.drop_duplicates()
print(df)

    Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter
1       2  1Ef7b82A4CAAD10    Preston    Lozano
2       3  6F94879bDAfE5a6        Roy     Berry
3       4  5Cef8BFA16c5e3c      Linda     Olsen
4       5  053d585Ab6b3159     Joanna    Bender
..    ...              ...        ...       ...
95     96  cb8E23e48d22Eae       Karl     Greer
96     97  CeD220bdAaCfaDf       Lynn  Atkinson
97     98  28CDbC0dFe4b1Db       Fred    Guerra
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer
99    100  2354a0E336A91A1   Clarence    Haynes

                            Company               City  \
0                   Rasmussen Group       East Leonard
1                       Vega-Gentry  East Jimmychester
2                     Murillo-Perry      Isabelborough
3   Dominguez, Mcmillan and Donovan         Bensonview
4          Martin, Lang and Andrade     West Priscilla
..                              ...                ...
95                        Carey LLC       East Richard
96            Ware, Burns and Oneal       New Bradview
97                    Schmitt-Jones         Ortegaland
98               Fitzgerald-Harrell    Lake Elijahview
99               Le, Nash and Cross          Judymouth

                       Country                 Phone 1  \
0                        Chile            229.077.5154
1                     Djibouti              5153435776
2          Antigua and Barbuda         +1-539-402-0259
3           Dominican Republic  001-808-617-6467x12895
4   Slovakia (Slovak Republic)  001-234-203-0635x76146
..                         ...                     ...
95                      Guyana     (188)169-1674x58692
96                   Sri Lanka         +1-846-706-2218
97             Solomon Islands    +1-753-067-8419x7170
98                       Aruba           (530)311-9786
99                    Honduras           (753)813-6941

                   Phone 2                           Email Subscription Date  \
0         397.884.0519x718        zunigavanessa@smith.info        2020-08-24
1         686-620-1820x944                 vmata@colon.com        2021-04-23
2      (496)978-3969x58947             beckycarr@hogan.com        2020-03-25
3          +1-813-324-8756     stanleyblackwell@benson.org        2020-06-02
4    001-199-446-3860x3486         colinalvarado@miles.net        2021-04-17
..                     ...                             ...               ...
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30
96            605.413.3198               vkemp@ferrell.com        2021-07-10
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11
99            783.639.1472          colleen91@faulkner.biz        2020-03-11

                              Website
0          http://www.stephenson.com/
1               http://www.hobbs.com/
2            http://www.lawrence.com/
3          http://www.good-lyons.com/
4         https://goodwin-ingram.com/
..                                ...
95            http://hayes-perez.com/
96         https://novak-allison.com/
97              https://www.ross.com/
98               http://watkins.info/
99  http://www.hatfield-saunders.net/

[100 rows x 12 columns]

In [ ]:
df.head(20)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
5,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/
6,7,EA4d384DfDbBf77,Darren,Peck,"Lester, Woodard and Mitchell",Lake Ana,Pitcairn Islands,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
8,9,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
9,10,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/
10,11,216E205d6eBb815,Carl,Schroeder,"Oconnell, Meza and Everett",Shannonville,Guernsey,637-854-0256x825,114.336.0784x788,kirksalas@webb.com,2021-10-20,https://simmons-hurley.com/
11,12,CEDec94deE6d69B,Jenna,Dodson,"Hoffman, Reed and Mcclain",East Andrea,Vietnam,(041)737-3846,+1-556-888-3485x42608,mark42@robbins.com,2020-11-29,http://www.douglas.net/
12,13,e35426EbDEceaFF,Tracey,Mata,Graham-Francis,South Joannamouth,Togo,001-949-844-8787,(855)713-8773,alex56@walls.org,2021-12-02,http://www.beck.com/
13,14,A08A8aF8BE9FaD4,Kristine,Cox,Carpenter-Cook,Jodyberg,Sri Lanka,786-284-3358x62152,+1-315-627-1796x8074,holdenmiranda@clarke.com,2021-02-08,https://www.brandt.com/
14,15,6fEaA1b7cab7B6C,Faith,Lutz,Carter-Hancock,Burchbury,Singapore,(781)861-7180x8306,207-185-3665,cassieparrish@blevins-chapman.net,2022-01-26,http://stevenson.org/
15,16,8cad0b4CBceaeec,Miranda,Beasley,Singleton and Sons,Desireeshire,Oman,540.085.3135x185,+1-600-462-6432x21881,vduncan@parks-hardy.com,2022-04-12,http://acosta.org/
16,17,a5DC21AE3a21eaA,Caroline,Foley,Winters-Mendoza,West Adriennestad,Western Sahara,936.222.4746x9924,001-469-948-6341x359,holtgwendolyn@watson-davenport.com,2021-03-10,http://www.benson-roth.com/
17,18,F8Aa9d6DfcBeeF8,Greg,Mata,Valentine LLC,Lake Leslie,Mozambique,(701)087-2415,(195)156-1861x26241,jaredjuarez@carroll.org,2022-03-26,http://pitts-cherry.com/
18,19,F160f5Db3EfE973,Clifford,Jacobson,Simon LLC,Harmonview,South Georgia and the South Sandwich Islands,001-151-330-3524x0469,(748)477-7174,joseph26@jacobson.com,2020-09-24,https://mcconnell.com/
19,20,0F60FF3DdCd7aB0,Joanna,Kirk,Mays-Mccormick,Jamesshire,French Polynesia,(266)131-7001x711,(283)312-5579x11543,tuckerangie@salazar.net,2021-09-24,https://www.camacho.net/

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Index         100 non-null    int64
 1   Name          100 non-null    object
 2   Description   100 non-null    object
 3   Brand         100 non-null    object
 4   Category      100 non-null    object
 5   Price         100 non-null    int64
 6   Currency      100 non-null    object
 7   Stock         100 non-null    int64
 8   EAN           100 non-null    int64
 9   Color         100 non-null    object
 10  Size          100 non-null    object
 11  Availability  100 non-null    object
 12  Internal ID   100 non-null    int64
dtypes: int64(5), object(8)
memory usage: 10.3+ KB

In [10]:
df.tail()

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
95,96,Router,Investment everything story buy.,Atkinson Inc,Laptops & Computers,375,USD,703,3330396409604,Gainsboro,8x10 in,limited_stock,55
96,97,Fast Thermostat Microphone Scooter,Nature notice themselves news.,Shea Ltd,Beauty & Personal Care,289,USD,727,9265397743935,White,Extra Large,backorder,25
97,98,Eco Heater Toaster Stove Silent Sense,Understand still or summer rule.,West Ltd,Cleaning Supplies,232,USD,998,5505866454530,OldLace,Small,limited_stock,20
98,99,Clean Blender Scale Lite,Final art some push.,"Bell, Gamble and Barrett",Camping & Hiking,241,USD,391,3893594435450,Aquamarine,5x7 in,limited_stock,5
99,100,Smart Lamp,However public major baby.,"Hebert, Hughes and Trujillo",Bedding & Bath,71,USD,518,8264263605712,Brown,Medium,limited_stock,3

In [11]:
df.count()

Index           100
Name            100
Description     100
Brand           100
Category        100
Price           100
Currency        100
Stock           100
EAN             100
Color           100
Size            100
Availability    100
Internal ID     100
dtype: int64